language: node_js

node_js:
  - "6"
  - "node"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
- npm install

script:
- npm run prettier-code
- npm run lint
- npm run style-lint
- npm run test
